name: Check CVEs
description: Run grondig

inputs:
  request:
    description: "Query entries in json"
    required: true
  url:
    description: "Grondig endpoint url"
    default: ''
  gh-token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  result:
    description: 'list of cves per uid, in json'
    value: ${{ steps.check.outputs.result }}

runs:
  using: composite
  steps:
    - name: Get tools and databases
      shell: bash
      if: ${{ inputs.url == '' }}
      run: |
        curl -sL -H "Authorization: Bearer ${{ inputs.gh-token }}" -o post.db.xz \
            https://github.com/analogdevicesinc/linux-security-vulns/releases/download/latest/post.db.xz
        xz --decompress post.db.xz

        curl -sL -H "Authorization: Bearer ${{ inputs.gh-token }}" -o grondig \
            https://github.com/analogdevicesinc/linux-security-vulns/releases/download/latest/grondig
        chmod +x grondig

    - name: Check
      id: check
      shell: bash
      run: |
        [[ "${{ runner.debug }}" == "1" ]] && set -x

        if [[ -n "${{ inputs.url }}" ]]; then
          result=$(curl -sS -k "${{ inputs.url }}" \
            -H 'Content-Type: application/json' \
            -d '${{ inputs.request }}')
        else
          result=$(printf '%s' '${{ inputs.request }}' | \
              ./grondig --post-db ./post.db)
        fi

        echo "$result"

        echo 'result<<EOF' >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
