name: Build CVE database
run-name: Build security vulnerabilities database
on:
  workflow_dispatch:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # to delete existing cache

    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgit2-dev just meson cargo

    - name: Build
      run: |
        [[ "${{ runner.debug }}" == "1" ]] && set -x

        get_file () {
          curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o $1 \
              https://raw.githubusercontent.com/${{ github.repository }}/ci/$1
        }

        get_file build-cve-db.sh
        get_file build-cve-files-db.py

        source ./build-cve-db.sh
        build-cve-db
        python3 build-cve-files-db.py

    - name: Delete existing CVE db cache
      run: |
        gh_api () {
          curl -fL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$@"
        }

        cache-exists () {
          gh_api "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=$1" \
            | jq -e '.total_count > 0' > /dev/null
        }

        cache-delete () {
          gh_api -X DELETE \
            "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=$1"
        }

        cache-exists linux-security-vulns && cache-delete linux-security-vulns

    - name: Save CVE db to cache
      uses: actions/cache/save@v5
      with:
        key: linux-security-vulns
        path: |
          vulns/tools/target/release/strak
          vulns/tools/verhaal/verhaal.db
          cve-files.db
