name: CVE artifact scan (score demo)
run-name: CVE artifact scan (score demo) ${{ inputs.repository }}@${{ inputs.ref }}
# This is a DEMO workflow, at scale, you maintain, post.db, and nvd cve'
# as proper databases and query them directly.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag, SHA reference'
        required: true
        type: string
      repository:
        description: "Repository"
        type: choice
        options:
        - adi/linux

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  check:
    name: CVE artifact scan
    uses: analogdevicesinc/linux-security-vulns/.github/workflows/check-artifact.yml@ci
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
    permissions:
      contents: read
      id-token: write
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}

  enrich-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: check
    steps:
    - uses: analogdevicesinc/doctools/blank@action

    - name: Merge result
      run: |
        # Merge result
        [[ "${{ runner.debug }}" == "1" ]] && set -x
        git fetch origin data:data
        git switch data

        ref="${{ inputs.ref }}"
        ref=$(echo "$ref" | sed 's|/|-|g')
        echo '${{ needs.check.outputs.result }}' > result.json
        jq -cn \
          --arg ref "${{ inputs.ref }}" \
          --arg sha "${{ needs.check.outputs.sha }}" \
          --arg modified "$(date -u +%Y-%m-%dT%H:%M:%S.%6NZ)" \
          --slurpfile result result.json \
          '{"ref": $ref, "sha": $sha, "modified": $modified, "result": $result[0]}' \
          > "${ref}.json"
        rm result.json

        ls refs-*.json | jq -nR '[inputs]' > refs.json

    - name: Build scores file
      # DEMO step, you should have a db table with the CVEs scores.
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: |
        # Build scores file
        enrich_cves=$(mktemp -t check.XXX.py)
        all_zip=$(mktemp -t all.XXX.zip)
        curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o "$enrich_cves" \
            https://raw.githubusercontent.com/analogdevicesinc/linux-security-vulns/ci/enrich-cves.py
        [ -f scores.json ] || echo '{}' > scores.json
        python3 "$enrich_cves" "scores.json"
        rm "$enrich_cves"

    - name: Commit
      run: |
        git add .
        git commit -m "deploy: ${{ inputs.ref }}" --allow-empty

    - name: Setup merge driver
      run: |
        curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o json-merge.py \
          https://raw.githubusercontent.com/analogdevicesinc/linux-security-vulns/ci/json-merge.py

        git config merge.json.name "JSON merge driver"
        git config merge.json.driver "python3 ./json-merge.py %O %A %B %L %P"
        git config merge.json.recursive binary
        echo '*.json merge=json' >> .gitattributes

    - name: Deploy
      run: |
        while ! git push origin HEAD:data ; do
          git pull --no-rebase origin data
        done
