name: Check CVEs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Kernel version tag'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: analogdevicesinc/linux-security-vulns/check-tag@ci
      id: check
      with:
        tag: ${{ inputs.tag }}

    - name: Create summary
      run: |
        cves='${{ steps.check.outputs.cves }}'
        len=$(echo "$cves" | jq length)

        echo "## CVEs in ${{ inputs.tag }}: $len" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| | | | | | |" >> $GITHUB_STEP_SUMMARY
        echo "|-|-|-|-|-|-|" >> $GITHUB_STEP_SUMMARY
        echo "$cves" | jq -r '
          . as $in |
          range(0; length; 6) |
          $in[.:.+6] |
          "| " + (map(.) | join(" | ")) + " |"' >> $GITHUB_STEP_SUMMARY
