name: CVE tag scan
run-name: CVE tag scan ${{ inputs.repository }}@${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Kernel version tag'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build request
      id: build
      run: |
        request=$(jq -cn \
            --arg tag "${{ inputs.tag }}" \
            '{ ($tag): { "stable-tag": $tag, "cherry-picked": [], "compiled-files": [] } }')
        echo "request=$request" >> $GITHUB_OUTPUT

    - uses: analogdevicesinc/linux-security-vulns/check@ci
      id: check
      with:
        request: ${{ steps.build.outputs.request }}

    - name: Create summary
      run: |
        result='${{ steps.check.outputs.result }}'
        cves=$(echo "$result" | jq --arg tag "${{ inputs.tag }}" '.[$tag].cves')
        len=$(echo "$cves" | jq length)

        echo "## CVEs in ${{ inputs.tag }}: $len" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| | | | | | |" >> $GITHUB_STEP_SUMMARY
        echo "|-|-|-|-|-|-|" >> $GITHUB_STEP_SUMMARY
        echo "$cves" | jq -r '
          . as $in |
          range(0; length; 6) |
          $in[.:.+6] |
          "| " + (map(.) | join(" | ")) + " |"' >> $GITHUB_STEP_SUMMARY
