name: Check CVEs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Kernel version tag'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Restore artifacts
      uses: actions/cache/restore@v5
      with:
        key: cve-db-${{ github.sha }}
        restore-keys: cve-db-
        path: |
          vulns/tools/target/release/strak
          vulns/tools/verhaal/verhaal.db
        fail-on-cache-miss: true

    - name: Check
      run: |
        [[ "${{ runner.debug }}" == "1" ]] && set -x

        get_file () {
          curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o $1 \
              https://raw.githubusercontent.com/${{ github.repository }}/ci/$1
        }

        get_file get-cve-list.sh

        chmod +x vulns/tools/target/release/strak

        cve_all=$(mktemp)
        source ./get-cve-list.sh

        get-cve-list "${{ inputs.tag }}" "$cve_all"

        cat "$cve_all" >> $GITHUB_STEP_SUMMARY
